### ISSUE TITLE
CellProfiler wiki is missing

### ISSUE THREAD

**Issue by trebacz626** [jump-cellpainting/2023_Chandrasekaran_submitted#82]
![image](https://github.com/jump-cellpainting/2023_Chandrasekaran_submitted/assets/26091073/9b2fcb57-6a8a-49f7-ae46-a7246aa6d59d)

![image](https://github.com/jump-cellpainting/2023_Chandrasekaran_submitted/assets/26091073/fae5716e-e7be-42c4-9043-541ea26ed495)

**Comment by niranjchandrasekaran** [comment]
Thank you @trebacz626! I have updated the link.
